---
title: "session-07-functions"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Functions tutorial

## Set up some test data

```{r load data}
airtemps <- c(212, 78.3, 30, 32)
celsius1 <- (airtemps[1]-32)*5/9
celsius2 <- (airtemps[2]-32)*5/9
celsius3 <- (airtemps[3]-32)*5/9
celsius4 <- (airtemps[4]-32)*5/9
```

## create a custom function
```{r create-function}
# custom function here
fahr_to_celsius <- function(fahr) {
  celsius <- (fahr-32)*5/9
  return(celsius)
}

# try it out
celsius5 <- fahr_to_celsius(airtemps[1])
celsius5

celsius5 == celsius1
```

## apply function to whole df
```{r vectorized}
celsius <- fahr_to_celsius(airtemps)
celsius
```

## on your own
```{r}
# do the opposite calculation now
celsius_to_fahr <- function(celsius) {
  fahr <- (celsius*9/5) + 32
  return(fahr)
}

fahr <- celsius_to_fahr(celsius)

# check?
fahr == airtemps
```


```{r}
convert_temps <- function(fahr) {
  celsius <- (fahr-32)*5/9
  kelvin <- celsius + 273.15
  return(list(fahr=fahr, celsius=celsius, kelvin=kelvin))
}

temps_df <- data.frame(convert_temps(seq(-100,100,10)))
temps_df
```



# create custom theme for ggplot
```{r themes}
# create a theme
custom_theme <- function(base_size=9) {
  ggplot2::theme(
    axis.ticks = ggplot2::element_blank(),
    text = ggplot2::element_text(family='Helvetica', color='gray30', size=base_size)
  )
}

# try it out!
library(ggplot2)
ggplot(temps_df, aes(fahr, celsius))+
  geom_point()+
  custom_theme()
```

```{r}
scatterplot <- function(df, point_size=2, font_size=9) {
  ggplot(df, mapping=aes(x=fahr, y=celsius, color=kelvin)) +
    geom_point(size=point_size)+
    custom_theme(font_size)
}

scatterplot(temps_df, point_size=3, font_size=16)
```


